name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
       
  
    - name: Build with Ant
      run: javac src/Main.java -d out
      
    - name: Rodando Programa
      run: java -cp out Main

    - name: mensagem de sucesso
      run: echo deu certooooooooooooooooooo!
